// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL7fiMeeLtOn1Tf5JIS3iDprnUD0BaQ9c',
    appId: '1:65479730759:web:7526fb0f90d44945917362',
    messagingSenderId: '65479730759',
    projectId: 'agatha-flutter-gdrive',
    authDomain: 'agatha-flutter-gdrive.firebaseapp.com',
    storageBucket: 'agatha-flutter-gdrive.appspot.com',
    measurementId: 'G-GFLGEEPX05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbF349kk46Pot88kLiY4nYhEQRL33Ht1I',
    appId: '1:65479730759:android:25076e801c103fcd917362',
    messagingSenderId: '65479730759',
    projectId: 'agatha-flutter-gdrive',
    storageBucket: 'agatha-flutter-gdrive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABsfIgcSdSyL2Rj0TjRvuEbisFc1Tq_lI',
    appId: '1:65479730759:ios:2940557547a06ec4917362',
    messagingSenderId: '65479730759',
    projectId: 'agatha-flutter-gdrive',
    storageBucket: 'agatha-flutter-gdrive.appspot.com',
    androidClientId: '65479730759-d6q7aqndvhq84hfc0niip3mabnvdehqo.apps.googleusercontent.com',
    iosClientId: '65479730759-7n8lpqhitnhcon4ep0hq94dph14s5qq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.arepFlutterSheetDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABsfIgcSdSyL2Rj0TjRvuEbisFc1Tq_lI',
    appId: '1:65479730759:ios:2940557547a06ec4917362',
    messagingSenderId: '65479730759',
    projectId: 'agatha-flutter-gdrive',
    storageBucket: 'agatha-flutter-gdrive.appspot.com',
    androidClientId: '65479730759-d6q7aqndvhq84hfc0niip3mabnvdehqo.apps.googleusercontent.com',
    iosClientId: '65479730759-7n8lpqhitnhcon4ep0hq94dph14s5qq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.arepFlutterSheetDrive',
  );
}
